# -*- coding: utf-8 -*-
"""[12_2] Postman

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDSEFD7Lkz6ZpgH-c4MYs5OErS9rFkss
"""

import requests
import json

url = "https://openapi.koreainvestment.com:9443/oauth2/tokenP"

payload = json.dumps({
  "grant_type": "client_credentials",
  "appkey": "",
  "appsecret": ""
})
headers = {
  'content-type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)

from google.colab import userdata
userdata.get('temp2')

import requests
import json

url = "https://openapi.koreainvestment.com:9443/uapi/domestic-stock/v1/quotations/inquire-price?fid_cond_mrkt_div_code=J&fid_input_iscd=005930"

payload = ""
headers = {
  'content-type': 'application/json',
  'authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0b2tlbiIsImF1ZCI6ImI4MzA2NmMzLTE2MTYtNGQ0OC1hMjUzLWIyM2JjNTNjZjg2YSIsInByZHRfY2QiOiIiLCJpc3MiOiJ1bm9ndyIsImV4cCI6MTcyNDg5MzM4MywiaWF0IjoxNzI0ODA2OTgzLCJqdGkiOiJQUzB2ZjRORTIzdktQbzFhTVcxaDd5WFVoSFViUEZhMVByUlkifQ.T6ngm4gh2-GPwK6lCN2TIe28kAEm_xfr2p7eExc7yq53aGKoa8vzh3CLLo44DXhdukzH4tnPjqXtD-CxTuRmGw',
  'appkey': '',
  'appsecret': '',
  'tr_id': 'FHKST01010100'
}

response = requests.request("GET", url, headers=headers, data=payload)

print(response.text)

86400/60/60

response.json()

json.loads(response.text)["output"]['stck_prpr']



"""# real-time(?)"""

import time
import requests
import json

try:
    while True:
        response = requests.request("GET", url, headers=headers, data=payload)
        print(json.loads(response.text)["output"]['stck_prpr'])
        time.sleep(1.0)
except KeyboardInterrupt:
    print("Process interrupted by user. Exiting...")

"""How can I add keyboard interrupt?"""

import requests

# GET request to echo back the headers sent
response = requests.get('https://postman-echo.com/get?foo1=bar1&foo2=bar2')
print(response.json())

# POST request to echo back the data sent
data = {
    'foo1': 'bar1',
    'foo2': 'bar2'
}
response = requests.post('https://postman-echo.com/post', data=data)
print(response.json())

