# -*- coding: utf-8 -*-
"""[5_3] registry pattern

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Trb9df6XuP8taToKXipybLoTO0VgM0AC
"""

a = dict()

a

a["abc"] = "something"

a

a["aaa"] = 1234

a

a["aaa"]

"""### Systematic way"""

class Demo:

    def __init__(self):
        self._buffers = dict()

    def register_buffer(self, name, content):
        self._buffers[name] = content

    def named_buffers(self):
        for name, content in self._buffers.items():
            yield name, content

    def buffers(self):
        for _, content in self.named_buffers():
            yield content

    def get_buffer(self, name):
        return self._buffers[name]

a = Demo()

a.register_buffer("sth", "somebody")

a.register_buffer("aaa", "anyone")

for i in a.named_buffers():
    print(i)

for i in a.buffers():
    print(i)

a.get_buffer("sth")

for i in a.named_buffers():
    print(i)

for i in a.buffers():
    print(i)

a.register_buffer("abc", 1234)

